name: Discord Commit Notifier

on:
  push:
    branches:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit payload to Discord Bot
        env:
          URL: http://${{ secrets.DISCORDBOT }}:3000/github-commits
        run: |
          curl -sS -X POST "$URL" \
            -H 'Content-Type: application/json' \
            --data-binary "@$GITHUB_EVENT_PATH"